import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ConnectKitButton } from "connectkit";

function ConnectDiv() {
  return (
    <div className={styles.connectdiv}>
      <ConnectKitButton />
    </div>
  );
}

function TitleDiv() {
  return (
    <div>
      <h1 className={styles.title}>TipJar</h1>
      <p className={styles.description}>Toss a coin to the witcher ✨</p>
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectDiv />
        <TitleDiv />
      </main>
    </div>
  );
};

export default Home;
